### ISSUE TITLE
不生成jsessionid导致Session无法跨请求～～

### ISSUE THREAD

**Issue by kttis** [x-hansong/RedisHttpSession#1]
不知道是不是我的问题，Session是可以放到redis中，但是只对当前请求生效,新请求因为没有写入jsessionid导致无法追踪用户～～希望楼主答疑,刚看了一下文档是请求头有一个ｘａｕｔｈ域存放的Sessionid,但是在不同的语言时候怎么解决呢？

**Comment by x-hansong** [comment]
请求的header里面会有x-auth-token字段，这个就是sessionid，客户端请求的时候需要在header中手动加入x-auth-token字段才能追踪到。不需要写入jsessionid，只要在请求中附带x-auth-token字段，目前还不支持用cookie来跟踪session，后续我会加上这个功能。如果你真的想用redis存储session，推荐你使用 spring-session，这个更加完善一点，但也复杂一点。

**Comment by kttis** [comment]
谢谢
