### ISSUE TITLE
Spring-Example 中Controller， json转map为null

### ISSUE THREAD

**Issue by Xarrow** [x-hansong/RedisHttpSession#2]
![qq 20170213153241](https://cloud.githubusercontent.com/assets/4395604/22874778/f7aa3b18-f202-11e6-85a4-17e785834145.png)
![qq 20170213153850](https://cloud.githubusercontent.com/assets/4395604/22874777/f77ba9ec-f202-11e6-9756-3ad9f3ef2bbc.png)
![Uploading QQ截图20170213153241.png…]()

**Comment by Xarrow** [comment]
应该是 json 不是json格式的字符，转json失败

**Comment by x-hansong** [comment]
你图中请求失败是因为使用了表单提交post请求，这种方式在response body会产生"name=test&password=123"格式的字符串，最好通过ajax的post方法，手动设置request body的内容为：`{ "name":"test", "password":"123"}`的json字符串。
